# Site settings
title: Programming Life
header-img: img/home-bg.png
email: alyxanderthibodeaux@gmail.com
copyright_name: CodeAlyx
description: > # this means to ignore newlines until "baseurl:"
  Making My Own Reality
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  CodeAlyx
learn_profile: CodeAlyx
email_username: alyxanderthibodeaux@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
